### ISSUE TITLE
tS Field Testing Feedback

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#609]
There are several issues that have come up that we need to address in tS.  This is a meta ticket that will reference individual issues.  Here is a start:

* [x] #606 Test backup and restore
* [x] #675 Unify backup/export file format?
* [x] #608 Add Timestamp to "Import from Storage"
* [x] unfoldingWord-dev/Door43#166 tA needs to include the misc files (statement of faith, guidelines, etc), so that they can be translated more easily in tS
* [x] unfoldingWord-dev/tools#105 Publish tW to uW Catalog - tW needs to be translatable
* [x] unfoldingWord-dev/translationDatabaseWeb#103 translationNotes needs to be translatable as a first class project
* [x] unfoldingWord-dev/tools#117 Publish tQ to uW Catalog so that they can be translated in tS
* [x] unfoldingWord-dev/tools#113 - Relates to the above 3 issues
* [x] #44 Revision history - Providing access to the revision history that exists would *hugely* help translation teams (even if only to provide peace of mind that they can easily revert back to a previous version)
* [ ] #563 - Creating a tS tablet mesh over wifi would be incredibly helpful for keeping multiple tablets in sync.  Common use case is to want to sync multiple tablets to 1 at the end of a translation event so that the 1 tablet can be taken to an Internet location for uploading.
* [ ] #117 - Bluetooth sync would be very helpful for non-wifi locations
* [x] #555 Make restoring from backup easier
* [x] #502 Allow restoring from a backup pushed to the server
* [x] #606 Test manual project export for backups while editing multiple projects. 
* [x] #610 Verse markers are inhibiting translation when placed at the end of the translation text.
* [x] #611 Auto backup needs to include translation notes.

Anything else?

**Comment by neutrinog** [comment]
I added a few.
